### ISSUE TITLE
NS 3 weird error: No view found for id 0x3 (unknown) for fragment MapFragment{29e82fc #3 id=0x3 MAP_FRAGMENT}

### ISSUE THREAD

**Issue by randy-johnson** [dapriett/nativescript-google-maps-sdk#151]
Hello.

I am working on getting our app to update to NS 3.0

I am running this version in package.json

    "nativescript-google-maps-sdk": "2.0.3",

Here is the error I get when trying to load our map:

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to resume activity {com.myApp/com.tns.NativeScriptActivity}: java.lang.IllegalArgumentException: No view found for id 0x3 (unknown) for fragment MapFragment{29e82fc #3 id=0x3 MAP_FRAGMENT}
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3400)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.IllegalArgumentException: No view found for id 0x3 (unknown) for fragment MapFragment{29e82fc #3 id=0x3 MAP_FRAGMENT}

```

Any ideas on what this could mean?

**Comment by randy-johnson** [comment]
Do you have any ideas on what this could be?   I have removed platform, node modules and added back the platform and that did not help.   I did get the basic example working but haven't had any luck figuring out what is causing this issue.

This is working fine in our NS 2.x branch but having no luck with NS 3.0

**Comment by FoulWeather** [comment]
I see the same thing when I replace the GridLayout in the basic example with a TabView. I haven't been able to pinpoint what is happening yet.

**Comment by dapriett** [comment]
Try the latest version, that should hopefully resolve your issue.

**Comment by randy-johnson** [comment]
I tracked it down this past weekend to using a a dependency observable  which is deprecated in NS3.  Once I discovered that everything was fine.  I haven't upgraded to the new version yet.  Thank You for the follow up @dapriett.
