### ISSUE TITLE
NS3 Running basic example

### ISSUE THREAD

**Issue by randy-johnson** [dapriett/nativescript-google-maps-sdk#152]
when I run the following code I get the error below the code.  using 2.0.3

```
<Page xmlns="http://www.nativescript.org/tns.xsd" xmlns:maps="nativescript-google-maps-sdk" loaded="pageLoaded">
    <GridLayout>
        <maps:mapView latitude="{{ latitude }}" longitude="{{ longitude }}"
                      zoom="{{ zoom }}" bearing="{{ bearing }}"
                      tilt="{{ tilt }}" i-padding="50,50,50,50" padding="{{ padding }}" 
                      mapReady="onMapReady" 
                      markerSelect="onMarkerSelect" 
                      cameraChanged="onCameraChanged" 
        />
    </GridLayout>
</Page> 
```

```
05-05 14:53:37.879  6225  6225 V JS      : com.tns.NativeScriptException:
05-05 14:53:37.879  6225  6225 V JS      : Calling js method onMapReady failed
05-05 14:53:37.879  6225  6225 V JS      :
05-05 14:53:37.879  6225  6225 V JS      : Error: Now use instance.nativeView instead of instance.android
05-05 14:53:37.879  6225  6225 V JS      : File: "file:///data/data/com.myApp/files/app/tns_modules/nativescript-google-maps-sdk/map-view.js, line: 200, column: 12
05-05 14:53:37.879  6225  6225 V JS      :
05-05 14:53:37.879  6225  6225 V JS      : StackTrace:
05-05 14:53:37.879  6225  6225 V JS      :      Frame: function:'get', file:'file:///data/data/com.myApp/files/app/tns_modules/nativescript-google-maps-sdk/map-view.js', line: 200, column: 19
05-05 14:53:37.879  6225  6225 V JS      :      Frame: function:'onMapReady', file:'file:///data/data/com.myApp/files/app/views/maptest/maptest5.js', line: 56, column: 16
05-05 14:53:37.879  6225  6225 V JS      :      Frame: function:'Observable.notify', file:'file:///data/data/com.myApp/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
05-05 14:53:37.879  6225  6225 V JS      :      Frame: function:'MapViewBase.notifyMapReady', file:'file:///data/data/com.myApp/files/app/tns_modules/nativescript-google-maps-sdk/map-view-common.js', line: 74, column: 14
05-05 14:53:37.879  6225  6225 V JS      :      Frame: function:'onMapReady', file:'file:///data/data/com.myApp/files/app/tns_modules/nativescript-google-maps-sdk/map-view.js', line: 144, column: 23
05-05 14:53:37.879  6225  6225 V JS      :
05-05 14:53:37.879  6225  6225 V JS      :
05-05 14:53:37.879  6225  6225 V JS      :      at com.tns.Runtime.callJSMethodNative(Native Method)
05-05 14:53:37.879  6225  6225 V JS      :      at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
05-05 14:53:37.879  6225  6225 V JS      :      at com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
05-05 14:53:37.879  6225  6225 V JS      :      at com.tns.Runtime.callJSMethod(Runtime.java:890)
05-05 14:53:37.879  6225  6225 V JS      :      at com.tns.Runtime.callJSMethod(Runtime.java:874)
05-05 14:53:37.879  6225  6225 V JS      :      at com.tns.Runtime.callJSMethod(Runtime.java:866)
05-05 14:53:37.879  6225  6225 V JS      :      at com.tns.gen.com.google.android.gms.maps.OnMapReadyCallback.onMapReady(OnMapReadyCallback.java:11)
05-05 14:53:37.879  6225  6225 V JS      :      at com.google.android.gms.maps.MapFragment$zza$1.zza(Unknown Source)
05-05 14:53:37.879  6225  6225 V JS      :      at com.google.android.gms.maps.internal.zzt$zza.onTransact(Unknown Source)
05-05 14:53:37.879  6225  6225 V JS      :      at android.os.Binder.transact(Binder.java:499)
05-05 14:53:37.879  6225  6225 V JS      :      at com.google.android.gms.maps.internal.bh.a(:com.google.android.gms.DynamiteModulesB:82)
05-05 14:53:37.879  6225  6225 V JS      :      at com.google.maps.api.android.lib6.impl.bh.run(:com.google.android.gms.DynamiteModulesB:1891)
05-05 14:53:37.879  6225  6225 V JS      :      at android.os.Handler.handleCallback(Handler.java:751)
05-05 14:53:37.879  6225  6225 V JS      :      at android.os.Handler.dispatchMessage(Handler.java:95)
05-05 14:53:37.879  6225  6225 V JS      :      at android.os.Looper.loop(Looper.java:154)
05-05 14:53:37.879  6225  6225 V JS      :      at android.app.ActivityThread.main(ActivityThread.java:6077)
05-05 14:53:37.879  6225  6225 V JS      :      at java.lang.reflect.Method.invoke(Native Method)
05-05 14:53:37.879  6225  6225 V JS      :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
05-05 14:53:37.879  6225  6225 V JS      :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
05-05 14:53:37.879  6225  6225 V JS      :  {} +2
0
```

Any idea what is going on here?

**Comment by randy-johnson** [comment]
Any Feedback?  still getting this error.

**Comment by dapriett** [comment]
Try using mapView.nativeView instead of mapView.android in your onMapReady function at 'file:///data/data/com.myApp/files/app/views/maptest/maptest5.js', line: 56, column: 16

**Comment by randy-johnson** [comment]
@dapriett ,

Yes that was it.  Thank You.

**Comment by giorgi-abashidze** [comment]
I have same error bt i cant understand the problem, i'm not using mapView.android nowhere..
my onmap ready function looks like this:

```
viewModel.onMapReady=(args)=>{

    viewModel.set('latitude',41.7244147);
    viewModel.set('longitude',44.7509121);
    viewModel.set('zoom',10);
    mapView = args.object;
    gMap = mapView.gMap;
   
}
```

**Comment by rjgpereira** [comment]
I'm having the same issue, and I also don't have any reference to "mapView.android". Just copied the example from the docs. Everything works fine in android, but I get a crash in iOS also with this message: 

"Now use instance.nativeView instead of instance.android"

**Comment by drangelod** [comment]
I ran into a similar issue with a Nativescript Vue app and solved it by setting a height on the map component (height="100%"). Worth a try if you're getting the "Now use instance.nativeView instead of instance.ios/android" and other solutions don't work.

**Comment by alexisconsuegra** [comment]
Hi 
I just installed the plugin and got the same error: Now use instance.nativeView instead of instance.ios
I don't have JavaScript code yest. Only
<maps:mapView latitude="{{ latitude }}" longitude="{{ longitude }}" mapAnimationsEnabled="false"
        zoom="8" bearing="180" tilt="35" padding="[80, 40, 40, 40]" />
So is it an issue with iOS?

**Comment by drangelod** [comment]
@alexisconsuegra Try adding a height to your XML map component and see if that fixes the error. (ie: height="100%" or height="500")

**Comment by alexisconsuegra** [comment]
@drangelod thanks. It worked.

**Comment by enstenr** [comment]
setting height worked for me too
