### ISSUE TITLE
Can't build for Android after adding plugin.

### ISSUE THREAD

**Issue by jmoody1988** [dapriett/nativescript-google-maps-sdk#156]
I added the plugin and when trying to run or build the app on android, I get the following fatal error that halts the process. Here is where the build process breaks. I can only build the app once I remove the nativescript-google-maps-sdk plugin.

---

:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class com.google.android.gms.auth.api.signin.internal.zzh conflict: D:\app-development\WeedAppPrototype\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\jars\classes.jar and D:\app-development\WeedAppPrototype\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-auth\8.3.0\jars\classes.jar
        at com.telerik.metadata.ClassRepo.addToCache(ClassRepo.java:21)
        at com.telerik.metadata.Builder.build(Builder.java:38)
        at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildMetadata'.
> Process 'command 'D:\Program Files\Java\jdk1.8.0_131\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 22.738 secs
Multiple errors were thrown:
Command gradlew.bat failed with exit code 1

**Comment by dapriett** [comment]
Looks like you're trying to use multiple versions of the Play Services SDK - 10.2.4 and 8.3.0.  Possibly a different plugin referencing an older version.  You can follow the readme directions on changing the version this plugin uses.
