### ISSUE TITLE
Map View / Scroll View App Crash

### ISSUE THREAD

**Issue by randy-johnson** [dapriett/nativescript-google-maps-sdk#206]
Hello,
[https://github.com/NativeScript/NativeScript/issues/3960#issuecomment-324662048](https://github.com/NativeScript/NativeScript/issues/3960#issuecomment-324662048)
One of the core team members (I think) added some comments to the above issue on how to resolve the issue with the app crashing with a scroll view / map view on the same page.  The team member suggested some plugin edits.

I am also having this same problem listed in the above issue.

-Randy

**Comment by randy-johnson** [comment]
Any thoughts on this @dapriett ?

**Comment by dapriett** [comment]
hey @randy-johnson, thanks for following up with the Nativescript team on the issue.  Sorry, haven't had a chance to look at this yet, but seems reasonable.  If you like, you can do a pull requests with the changes, I'll take a look and merge it in.

**Comment by shiv19** [comment]
Hey @randy-johnson ! I tried to fix it, but I couldn't
But luckily I have a work around, I've written the steps to follow it here
https://github.com/NativeScript/NativeScript/issues/4821

**Comment by vivekprajapati12011995** [comment]
I have also the same issue when I come back to the previous screen that has mapView implementation then
the application crashes with the following error. so please help me out to solve the issue **@dapriett**  and **`@shiv19`** 


 java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to com.telerik.android.primitives.widget.sidedrawer.SideDrawerState

**Comment by shiv19** [comment]
@vivekprajapati12011995 I've written a temporary workaround for it.
https://shiv19.com/how-to-fix-nativescript-google-maps-sdk-map-view-crash-inside-scroll-view/

**Comment by nmongiya** [comment]
When I am using android back button to navigate back to screen(that has MapView) , it is crashing with the following error in console
01-08 16:15:19.920 11863 11863 F zygote : java_vm_ext.cc:504] from java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[])
01-08 16:15:19.920 11863 11863 F zygote : java_vm_ext.cc:504] at com.tns.Runtime.callJSMethodNative(Native method)
01-08 16:15:19.920 11863 11863 F zygote : java_vm_ext.cc:504] at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
01-08 16:15:19.920 11863 11863 F zygote : java_vm_ext.cc:504] at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
01-08 16:15:19.920 11863 11863 F zygote : java_vm_ext.cc:504] at com.tns.Runtime.callJSMethod(Runtime.java:953)
01-08 16:15:19.920 11863 11863 F zygote : java_vm_ext.cc:504] at com.tns.Runtime.callJSMethod(Runtime.java:937)
01-08 16:15:19.920 11863 11863 F zygote : java_vm_ext.cc:504] at com.tns.Runtime.callJSMethod(Runtime.java:929)
01-08 16:15:20.013 11863 11863 F zygote : runtime.cc:492] at com.tns.Runtime.callJSMethodNative(Native method)
01-08 16:15:20.013 11863 11863 F zygote : runtime.cc:492] at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
01-08 16:15:20.013 11863 11863 F zygote : runtime.cc:492] at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
01-08 16:15:20.013 11863 11863 F zygote : runtime.cc:492] at com.tns.Runtime.callJSMethod(Runtime.java:953)
01-08 16:15:20.013 11863 11863 F zygote : runtime.cc:492] at com.tns.Runtime.callJSMethod(Runtime.java:937)
01-08 16:15:20.013 11863 11863 F zygote : runtime.cc:492] at com.tns.Runtime.callJSMethod(Runtime.java:929)
01-08 16:15:20.014 11863 11863 F zygote : runtime.cc:492] at com.tns.Runtime.callJSMethodNative(Native method)
01-08 16:15:20.014 11863 11863 F zygote : runtime.cc:492] at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
01-08 16:15:20.014 11863 11863 F zygote : runtime.cc:492] at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
01-08 16:15:20.014 11863 11863 F zygote : runtime.cc:492] at com.tns.Runtime.callJSMethod(Runtime.java:953)
01-08 16:15:20.014 11863 11863 F zygote : runtime.cc:492] at com.tns.Runtime.callJSMethod(Runtime.java:937)
01-08 16:15:20.014 11863 11863 F zygote : runtime.cc:492] at com.tns.Runtime.callJSMethod(Runtime.java:929)
01-08 16:15:20.059 11863 11863 F zygote : runtime.cc:500] from java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[])
01-08 16:15:20.060 11863 11863 F zygote : runtime.cc:500] at com.tns.Runtime.callJSMethodNative(Native method)
01-08 16:15:20.060 11863 11863 F zygote : runtime.cc:500] at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084) com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
01-08 16:15:20.060 11863 11863 F zygote : runtime.cc:500] at com.tns.Runtime.callJSMethod(Runtime.java:953)
com.tns.Runtime.callJSMethodImpl(Runtime.java:966) com.tns.Runtime.callJSMethod(Runtime.java:937)
01-08 16:15:20.060 11863 11863 F zygote : runtime.cc:500] at com.tns.Runtime.callJSMethod(Runtime.java:929)
com.tns.Runtime.callJSMethod(Runtime.java:953) 3) has died: fore TOP
01-08 16:15:20.060 11863 11863 F zygote : runtime.cc:500] at com.tns.Runtime.callJSMethod(Runtime.java:937)
01-08 16:15:20.060 11863 11863 F zygote : runtime.cc:500] at com.tns.Runtime.callJSMethod(Runtime.java:929)
ActivityManager: Process org.nativescript.FreshTracker (pid 11863) has died: fore TOP
ActivityManager: setHasOverlayUi called on unknown pid: 11863
