### ISSUE TITLE
Mapview crashes when using with NativeScript-Vue

### ISSUE THREAD

**Issue by andreMariano90** [dapriett/nativescript-google-maps-sdk#260]
When Trying to use nativescript with vue, the map simply crashes

Here is the code:
<template>
    <MapView :latitude="latitude" :ongitude="longitude" mapAnimationsEnabled="true" mapReady="onMapReady()", ref="map" v-model="map"  />
</template>

<script>
    import Vue from 'nativescript-vue';

    Vue.registerElement("MapView", () => require("nativescript-google-maps-sdk").MapView);

    export default {
        name: "mapa",
        data(){
            return {
                latitude: -25.3894267,
                longitude: -49.2722997
            }

        },
        methods: {
            onMapReady: function () {
                console.log("map created");
            }
        }
    }
</script>

and here is the package.json

{
  "name": "Sample Map",
  "version": "1.0.0",
  "description": "A native application built with NativeScript-Vue",
  "author": "Andre Mariano",
  "license": "MIT",
  "scripts": {
    "build": "webpack --env.tnsAction build",
    "build:android": "npm run build -- --env.android",
    "build:ios": "npm run build -- --env.ios",
    "debug": "webpack --watch --env.tnsAction debug",
    "debug:android": "npm run debug -- --env.android",
    "debug:ios": "npm run debug -- --env.ios",
    "watch": "webpack --watch --env.tnsAction run",
    "watch:android": "npm run watch -- --env.android",
    "watch:ios": "npm run watch -- --env.ios",
    "clean": "rimraf dist"
  },
  "dependencies": {
    "nativescript-cardview": "^2.0.5",
    "nativescript-drawingpad": "^2.1.1",
    "nativescript-google-maps-sdk": "^2.5.0",
    "nativescript-sqlite": "^2.0.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-sidedrawer": "^3.5.1",
    "nativescript-vue": "^1.3.0",
    "tns-core-modules": "~3.4.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.3",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "copy-webpack-plugin": "^4.4.2",
    "css-loader": "^0.28.10",
    "extract-text-webpack-plugin": "^3.0.2",
    "fs-extra": "^5.0.0",
    "nativescript-vue-externals": "^0.1.1",
    "nativescript-vue-loader": "^0.1.5",
    "nativescript-vue-target": "^0.1.0",
    "nativescript-vue-template-compiler": "^1.3.0",
    "node-sass": "^4.7.2",
    "ns-vue-loader": "^0.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^6.0.6",
    "vue-template-compiler": "^2.5.13",
    "webpack": "^3.11.0",
    "webpack-synchronizable-shell-plugin": "0.0.6",
    "winston-color": "^1.0.0"
  }
}

Everytime I get a  "A Frame must be used to navigate to a Page". This error  always shows up when a page can't be rendered
`System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: A Frame must be used to navigate to a Page.`

When going deeper in the Nativescript-vue lib I got this error after trying to create the element:

`undefined is not a constructor (evaluating 'new n')` but I couldn't go further

**Comment by hans00** [comment]
I solved
import MapViewBase every time before import sdk
```js
import { MapViewBase } from 'nativescript-google-maps-sdk/map-view-common';
```

**Comment by clintrobinson** [comment]
@hans00 Could you please post exactly what you did to get it working. I am having trouble getting this working as well.

**Comment by hans00** [comment]
Here is my code

main.js
```js
import Vue from 'nativescript-vue';

// ... some others

import { MapViewBase } from 'nativescript-google-maps-sdk/map-view-common';
Vue.registerElement('MapView', ()=> require('nativescript-google-maps-sdk').MapView)

// Vue ... $start();
```

Map.vue
```vue
<template>
	<Page>
		<GridLayout>
			<MapView row="0" :latitude="latitude" :longitude="longitude"  :zoom="zoom" :bearing="bearing" :tilt="tilt" :padding="padding" :minZoom="minZoom" :maxZoom="maxZoom" @mapReady="mapReady" @markerSelect="onMarkerSelect" />
		</GridLayout>
	<Page>
</template>

<script>
import { MapViewBase } from 'nativescript-google-maps-sdk/map-view-common';
import { Position, Marker } from "nativescript-google-maps-sdk";

export default {
	data () {
		return {
			latitude:  0,
			longitude: 0,
			zoom: 15,
			minZoom: 0,
			maxZoom: 22,
			bearing: 0,
			tilt: 0,
			padding: [40, 40, 40, 40],
			mapView: null,
		};
	},
	methods: {
		mapReady(args) {
			this.mapView = args.object
			this.mapView.infoWindowTemplate = `
				<StackLayout orientation="vertical" width="200">
					<Label text="{{title}}" className="title"/>
					<Label text="{{snippet}}" textWrep="true" class="snippet"/>
				</StackLayout>
			`
			const marker = new Marker()
			marker.position = Position.positionFromLatLng(0, 0)
			marker.title = 'Test'
			marker.snippet = 'test'
			marker.userData = {test: 'test'}
			this.mapView.addMarker(marker)
		},
		onMarkerSelect(args) {
			console.log(args.marker)
		}
	},
};
</script>
```

**Comment by dbilovd** [comment]
@hans00 A thousand <3 s for you. Thanks. It worked for me after months.

**Comment by DevPlus31** [comment]
Is it to use this code below instead:

` <MapView :latitude="latitude" :longitude="longitude" mapAnimationsEnabled="true"
         :zoom:="zoom" :minZoom="minZoom" :bearing="bearing" :padding="padding" @cameraMove="onCameraMove" @mapReady="mapReady">
            <StackLayout ~infoWindowTemplate>
                <Label :text="title" style="color: red;" />
            </StackLayout>
        </MapView>`

It's not working on my computer I wanted to know your thoughts guys

**Comment by ojcloveu** [comment]
I got error please help me


An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
    com.google.maps.api.android.lib6.drd.q.b(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):40)
    com.google.maps.api.android.lib6.auth.e.a(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):11)
    com.google.maps.api.android.lib6.impl.e.a(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):4)
    com.google.android.gms.maps.internal.b.a(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):24)
    com.google.android.gms.maps.internal.CreatorImpl.a(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):69)
    com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):38)
    com.google.android.gms.maps.internal.i.a(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):42)
    fc.onTransact(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):12)
    android.os.Binder.transact(Binder.java:499)
    com.google.android.gms.internal.maps.zza.transactAndReadException(Unknown Source)
    com.google.android.gms.maps.internal.zzf.zza(Unknown Source)
    com.google.android.gms.maps.MapView$zzb.createDelegate(Unknown Source)
    com.google.android.gms.dynamic.DeferredLifecycleHelper.zza(Unknown Source)
    com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(Unknown Source)
    com.google.android.gms.maps.MapView.onCreate(Unknown Source)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
    com.tns.Runtime.callJSMethod(Runtime.java:983)
    com.tns.Runtime.callJSMethod(Runtime.java:967)
    com.tns.Runtime.callJSMethod(Runtime.java:959)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
    android.app.Fragment.performCreateView(Fragment.java:2353)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
    android.app.BackStackRecord.run(BackStackRecord.java:816)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
    android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
    android.os.Handler.handleCallback(Handler.java:751)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6119)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
File: "file:///data/data/org.nativescript.application/files/app/app.js, line: 23321, column: 24

StackTrace: 
	Frame: function:'MapView.createNativeView', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 23321, column: 25
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 412, column: 35
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 206, column: 40
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 357, column: 18
	Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 346, column: 14
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 504, column: 24
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
	at com.tns.Runtime.callJSMethod(Runtime.java:983)
	at com.tns.Runtime.callJSMethod(Runtime.java:967)
	at com.tns.Runtime.callJSMethod(Runtime.java:959)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
	at android.app.Fragment.performCreateView(Fragment.java:2353)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
	at android.app.BackStackRecord.run(BackStackRecord.java:816)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
	at com.google.maps.api.android.lib6.drd.q.b(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):40)
	at com.google.maps.api.android.lib6.auth.e.a(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):11)
	at com.google.maps.api.android.lib6.impl.e.a(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):4)
	at com.google.android.gms.maps.internal.b.a(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):24)
	at com.google.android.gms.maps.internal.CreatorImpl.a(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):69)
	at com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):38)
	at com.google.android.gms.maps.internal.i.a(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):42)
	at fc.onTransact(:com.google.android.gms.dynamite_mapsdynamite@12874026@12.8.74 (040700-204998136):12)
	at android.os.Binder.transact(Binder.java:499)
	at com.google.android.gms.internal.maps.zza.transactAndReadException(Unknown Source)
	at com.google.android.gms.maps.internal.zzf.zza(Unknown Source)
	at com.google.android.gms.maps.MapView$zzb.createDelegate(Unknown Source)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zza(Unknown Source)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(Unknown Source)
	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
	... 20 more

**Comment by Erwol** [comment]
> import { MapViewBase } from 'nativescript-google-maps-sdk/map-view-common'; import { Position, Marker } from "nativescript-google-maps-sdk"; export default { data () { return { latitude: 0, longitude: 0, zoom: 15, minZoom: 0, maxZoom: 22, bearing: 0, tilt: 0, padding: [40, 40, 40, 40], mapView: null, }; }, methods: { mapReady(args) { this.mapView = args.object this.mapView.infoWindowTemplate = ` <StackLayout orientation="vertical" width="200"> <Label text="{{title}}" className="title"/> <Label text="{{snippet}}" textWrep="true" class="snippet"/> </StackLayout> ` const marker = new Marker() marker.position = Position.positionFromLatLng(0, 0) marker.title = 'Test' marker.snippet = 'test' marker.userData = {test: 'test'} this.mapView.addMarker(marker) }, onMarkerSelect(args) { console.log(args.marker) } }, };

Hello, do you remember or can check which version of this plugin were you using when you were able to make it work? Thanks!

**Comment by mriza1815** [comment]
In last nativescript-vue release, importing MapViewBase getting error.
Solution is just delete this import line and use as normal

**Comment by DevPlus31** [comment]
@mriza1815 After deleting MapViewBase I have another error which is: 

`Type Error: Cannot read property 'CameraPosition' of undefined`

Any solution ?

**Comment by DevPlus31** [comment]
It's working now I deleted the the platform then installed it again
