### ISSUE TITLE
java.lang.ClassCastException: android.widget.ImageView cannot be cast to android.view.ViewGroup

### ISSUE THREAD

**Issue by cnqiuxue** [dapriett/nativescript-google-maps-sdk#286]
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method finishUpdate failed

Error: java.lang.ClassCastException: android.widget.ImageView cannot be cast to android.view.ViewGroup
    android.app.BackStackRecord.configureTransitions(BackStackRecord.java:1303)
    android.app.BackStackRecord.beginTransition(BackStackRecord.java:1016)
    android.app.BackStackRecord.run(BackStackRecord.java:729)
    android.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1539)
    android.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:688)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1100)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:982)
    com.tns.Runtime.callJSMethod(Runtime.java:969)
    com.tns.Runtime.callJSMethod(Runtime.java:953)
    com.tns.Runtime.callJSMethod(Runtime.java:945)
    com.tns.gen.android.support.v4.view.PagerAdapter_view_69_32_FragmentPagerAdapter.finishUpdate(PagerAdapter_view_69_32_FragmentPagerAdapter.java:92)
    android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1062)
    android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:3089)
    android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:284)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1100)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:982)
    com.tns.Runtime.callJSMethod(Runtime.java:969)
    com.tns.Runtime.callJSMethod(Runtime.java:953)
    com.tns.Runtime.callJSMethod(Runtime.java:945)
    com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
    android.os.Handler.handleCallback(Handler.java:751)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6119)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
File: "file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js, line: 158, column: 41

StackTrace: 
	Frame: function:'FragmentPagerAdapter.finishUpdate', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js', line: 158, column: 42
	Frame: function:'TabView.setAdapterItems', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js', line: 448, column: 36
	Frame: function:'TabView.onUnloaded', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js', line: 401, column: 14
	Frame: function:'', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 92
	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
	Frame: function:'ViewBase.callUnloaded', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 14
	Frame: function:'ViewBase.unloadView', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 444, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 246, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
	Frame: function:'ViewBase.onUnloaded', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 245, column: 14
	Frame: function:'View.onUnloaded', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 218, column: 37
	Frame: function:'', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 92
	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
	Frame: function:'ViewBase.callUnloaded', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 14
	Frame: function:'ViewBase.unloadView', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 444, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 246, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 120, column: 40
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
	Frame: function:'ViewBase.onUnloaded', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 245, column: 14
	Frame: function:'View.onUnloaded', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 218, column: 37
	Frame: function:'', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 92
	Frame: function:'ViewBase.callFunctionWithSuper', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 304, column: 9
	Frame: function:'ViewBase.callUnloaded', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 315, column: 14
	Frame: function:'FrameBase.raiseCurrentPageNavigatedEvents', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 172, column: 22
	Frame: function:'FrameBase._updateBackstack', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 148, column: 14
	Frame: function:'Frame.setCurrent', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 186, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 578, column: 53
	Frame: function:'ZoneDelegate.invokeTask', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 398, column: 31
	Frame: function:'Zone.runTask', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 165, column: 47
	Frame: function:'ZoneTask.invoke', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 460, column: 38
	Frame: function:'timer', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1636, column: 29
	Frame: function:'invoke', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
	Frame: function:'ZoneDelegate.invoke', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 365, column: 26
	Frame: function:'Zone.runGuarded', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 138, column: 47
	Frame: function:'', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 116, column: 29
	Frame: function:'run', file:'file:///data/data/org.nativescript.angularnativescript/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1100)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:982)
	at com.tns.Runtime.callJSMethod(Runtime.java:969)
	at com.tns.Runtime.callJSMethod(Runtime.java:953)
	at com.tns.Runtime.callJSMethod(Runtime.java:945)
	at com.tns.gen.android.support.v4.view.PagerAdapter_view_69_32_FragmentPagerAdapter.finishUpdate(PagerAdapter_view_69_32_FragmentPagerAdapter.java:92)
	at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1062)
	at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:3089)
	at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:284)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1100)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:982)
	at com.tns.Runtime.callJSMethod(Runtime.java:969)
	at com.tns.Runtime.callJSMethod(Runtime.java:953)
	at com.tns.Runtime.callJSMethod(Runtime.java:945)
	at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.ClassCastException: android.widget.ImageView cannot be cast to android.view.ViewGroup
	at android.app.BackStackRecord.configureTransitions(BackStackRecord.java:1303)
	at android.app.BackStackRecord.beginTransition(BackStackRecord.java:1016)
	at android.app.BackStackRecord.run(BackStackRecord.java:729)
	at android.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1539)
	at android.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:688)
	... 24 more
```
![image](https://user-images.githubusercontent.com/26665435/40915551-154d11e2-682f-11e8-8e08-3b5d9c5c4238.png)
![image](https://user-images.githubusercontent.com/26665435/40915564-231b4c12-682f-11e8-9bb2-651440a8945b.png)

When I add xxx, the above exception appears.

add   this.mapView.addMarker(marker);

**Comment by NickIliev** [comment]
Confirming this one as a bug.

Steps to reproduce:
- use [this test app](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/NativeScript/issue-5897)
- navigate from the main page with tabView to a page with Map

**Comment by NickAtGit** [comment]
I see the same error sometimes with life sync. But after that it works...

**Comment by cnoter** [comment]
Please solve this ASAP!!!

**Comment by levu74** [comment]
Does we have workaround for this issue?

**Comment by keerl** [comment]
Same thing here. Any solutions yet?

**Comment by artdias90** [comment]
+1

**Comment by rolandoDev** [comment]
+1

**Comment by mriza1815** [comment]
+1

**Comment by NickIliev** [comment]
@mriza1815  @rolandoDev  @artdias90  @keerl  @FutureFutureTo @levu74 @Bolhy10 @Ross-Jo @cnoter @cnqiuxue @NickAtGit the issue can be solved by using the `TabView`as root in NativeScript 4.2.x

Here is [a demonstration application ](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/NativeScript/issue-5897).

The `app.component,html` hold the root tab view
```HTML
<TabView class="tab-view">
    <StackLayout *tabItem="{title: 'Tab1'}">
        <page-router-outlet></page-router-outlet>
    </StackLayout>
    <StackLayout *tabItem="{title: 'Tab2'}">
        <Label text="Some PAGE"   textWrap="true" class="h1"></Label>
    </StackLayout>
</TabView>
```

The routing table is a simple as (used lazily laoded map but you can use a component as well)
```JS
const routes: Routes = [
    { path: "", redirectTo: "/items", pathMatch: "full" },
    { path: "items", component: ItemsComponent },
    {
        path: "map",
        loadChildren: "./map/map.module#MapModule",
    },
];
```

The initial tab page (`items`)
```JS
import { Component } from "@angular/core";
import { RouterExtensions } from "nativescript-angular/router";
import { Page} from "tns-core-modules/ui/page";

@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent {

    constructor(private _routerExtensions: RouterExtensions, private _page: Page) {
        this._page.actionBarHidden = true;
     }

    navigate() {
        this._routerExtensions.navigate(['/map']);
    }
}
```

and the Map page (in  this case lazily laoded via map.module)
```JS
<GridLayout rows="400" >
    <MapView row="0" (mapReady)="onMapReady($event)" backgroundColor="lightgray"></MapView>
</GridLayout>
```

**Comment by hanreev** [comment]
@NickIliev, randomly selecting tab still reprodure this error with 3 tabs or more.
