### ISSUE TITLE
Failed to build plugin nativescript-google-maps-sdk

### ISSUE THREAD

**Issue by klever34** [dapriett/nativescript-google-maps-sdk#317]
Unable to apply changes on device: 0228010741401765. Error is: Failed to build plugin nativescript-google-maps-sdk : 
Error: Command ./gradlew failed with exit code 1 Error output: 
 
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':releaseCompileClasspath'.
> Could not find support-v4.aar (com.android.support:support-v4:26.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-v4/26.1.0/support-v4-26.1.0.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

tns version : 4.0.1

**Comment by PamilerinId** [comment]
Same Here in 2019

**Comment by klever34** [comment]
@PamilerinId are you using Nativescript-Vue 2.0?

**Comment by PamilerinId** [comment]
No, Nativescript-Angular

**Comment by rellikdb1978** [comment]
facing issue with android-29 and nativescript-google-maps-sdk

spawn: gradlew.bat "-p" "D:\work\git-repos\qooo\qooo\platforms\tempPlugin\nativescript_google_maps_sdk" "assembleRelease" "-PcompileSdk=android-29" "-PbuildToolsVersion=29.0.3"
Error: Could not find or load main class '
Caused by: java.lang.ClassNotFoundException: '
Failed to build plugin nativescript-google-maps-sdk :
Error: Command gradlew.bat failed with exit code 1
Error while executing action on device emulator-5554. The error is Error: Failed to build plugin nativescript-google-maps-sdk :
Error: Command gradlew.bat failed with exit code 1
    at Errors.failWithOptions (C:\Users\donny\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:147:28)
    at Errors.fail (C:\Users\donny\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:120:21)
    at AndroidPluginBuildService.<anonymous> (C:\Users\donny\AppData\Roaming\npm\node_modules\nativescript\lib\services\android-plugin-build-service.js:395:30)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\donny\AppData\Roaming\npm\node_modules\nativescript\lib\services\android-plugin-build-service.js:11:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'Exception',
  errorCode: 127,
  suggestCommandHelp: false,
  proxyAuthenticationRequired: false,
  printOnStdout: undefined,
  deviceIdentifier: 'emulator-5554'
}
