### ISSUE TITLE
Crash when use two mapViews inside the TabView and navigating beteen tabs

### ISSUE THREAD

**Issue by neumartin** [dapriett/nativescript-google-maps-sdk#318]
I have this page:

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" 
    xmlns:maps="nativescript-google-maps-sdk" loaded="onPageLoaded" navigatingTo="onNavigatingTo" class="page" actionBarHidden="true">

    <TabView id="tabViewContainer" selectedIndex="0" androidOffscreenTabLimit="5" androidTabsPosition="bottom" tabBackgroundColor="#002d5d" androidSelectedTabHighlightColor="red" tabTextColor="#ffffff" selectedTabTextColor="#ffffff">
        <TabViewItem title="Noticias" iconSource="res://menu_feed" class="tab-item" 
            xmlns:TabNoticias="views/noticias" badgeValue="3">
            <Frame defaultPage="views/noticias"></Frame>
        </TabViewItem>
        <TabViewItem title="Auto" iconSource="res://menu_auto" class="tab-item" 
            xmlns:TabAuto="views/auto">
            <Frame defaultPage="views/auto"></Frame>
        </TabViewItem>
        <TabViewItem title="Guantera" iconSource="res://menu_folder" class="tab-item" 
            xmlns:TabBox="views/guanteraborder-color:">
            <Frame defaultPage="views/guantera"></Frame>
        </TabViewItem>
        <TabViewItem title="Lugares" iconSource="res://menu_services" class="tab-item" 
            xmlns:TabServicios="views/lugares">
            <Frame defaultPage="views/lugares"></Frame>
        </TabViewItem>
        <TabViewItem title="Mas..." iconSource="res://menu_more" class="tab-item" 
            xmlns:TabMore="views/mas">
            <Frame defaultPage="views/mas"></Frame>
        </TabViewItem>
    </TabView>
</Page>
```

In TabViewItem title="Noticias" and TabViewItem title="Lugares" I place the mapView, when navigating between tabs I get this error:

"An uncaught Exception occurred on "main" thread.
java.lang.ClassCastException: com.google.maps.api.android.lib6.impl.ao cannot be cast to android.view.ViewGroup
	at android.app.FragmentTransition.configureTransitionsReordered(FragmentTransition.java:197)
	at android.app.FragmentTransition.startTransitions(FragmentTransition.java:116)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2202)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2148)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2049)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
"

And the second TabViewItem title="Auto" apear in blank, but if I navigate to other tab and back to "Auto" the tab renders ok.

If I use only one map in one tab, the issue disapear.

**Comment by neumartin** [comment]
@dapriett can you help me?

**Comment by neumartin** [comment]
@naderio @breningham @christocracy @nickcoury @rajivnarayana 
Can help me with this issue?
Thanks!!

**Comment by kandangit** [comment]
I have the same issue. The issue is not happening all the time but happens relatively often.
I have a component with a TabView and two tabs (in Angular). The first tab has a button which navigates to another component with the map. 

then the app crashes with that error.

Please, could you  help? Could this ve a nativescript issue instead?

**Comment by jnorkus** [comment]
I am seeing the same issue. Happens when opening a modal with a <page-router-outlet> second time.
