### ISSUE TITLE
NativeScript Google maps java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion

### ISSUE THREAD

**Issue by drubantsov** [dapriett/nativescript-google-maps-sdk#319]
https://stackoverflow.com/questions/53324898/nativescript-google-maps-java-lang-noclassdeffounderror-failed-resolution-of-l/53325072#53325072

**Comment by nmongiya** [comment]
This is happening with  android 28 and NS 5
```
An uncaught Exception occurred on "Thread-15" thread.
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
	at fa.b(:com.google.android.gms.dynamite_mapsdynamite@14582084@14.5.82 (100700-222134188):3)
	at ez.a(:com.google.android.gms.dynamite_mapsdynamite@14582084@14.5.82 (100700-222134188):3)
	at fb.a(:com.google.android.gms.dynamite_mapsdynamite@14582084@14.5.82 (100700-222134188):15)
	at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@14582084@14.5.82 (100700-222134188):6)
	at ee.a(:com.google.android.gms.dynamite_mapsdynamite@14582084@14.5.82 (100700-222134188):21)
	at ee.run(:com.google.android.gms.dynamite_mapsdynamite@14582084@14.5.82 (100700-222134188):8)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000024/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000024/MapsDynamite.apk!/lib/x86, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at ac.loadClass(:com.google.android.gms.dynamite_dynamiteloader@14582084@14.5.82 (100700-222134188):4)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 6 more

```

**Comment by NickIliev** [comment]
+1 - I am also hitting this one on Android P
