### ISSUE TITLE
Application crash on location.back() action after opening external application like camera or gallery

### ISSUE THREAD

**Issue by d-mh** [dapriett/nativescript-google-maps-sdk#363]
#### Application crash every time when I do below steps:
1. Load Google Maps on on main page (`home.component.ts`)
2. Navigate to second component (`event.component.ts`)
3. On `event.component.ts` I am opening camera (`NativeScript/nativescript-camera`) or gallery (`nativescript-imagepicker`)
4. Then cancel action (camera or image picker) 
5. Run `location.back()` action or press `back` button 
6. Crash (log below) 

What is interesting when I do `location.back()` or press `back` button on Android without opening camera or image picker, back action works great and without any errors.

I am thinking this issue is related to error below: 
```
System.err: Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class com.google.android.material.stateful.ExtendableSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x2. Make sure other views do not use the same id.
```
but I am not sure how to change id on View with Angular app ...

#### I am receiving this error:
```
System.err: An uncaught Exception occurred on "main" thread.

System.err: Calling js method onCreateView failed
System.err: Error: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class com.google.android.material.stateful.ExtendableSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x2. Make sure other views do not use the same id.

System.err:     android.view.View.onRestoreInstanceState(View.java:18663)

System.err:     android.view.View.dispatchRestoreInstanceState(View.java:18635)

System.err:     android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3829)

System.err:     android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3829)

System.err:     android.view.View.restoreHierarchyState(View.java:18613)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)

System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)

System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)

System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1109)

System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1089)

System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1081)

System.err:     com.tns.FragmentClass.onCreateView(FragmentClass.java:53)

System.err:     androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)

System.err:     androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)

System.err:     androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)

System.err:     androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)

System.err:     androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)

System.err:     androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)

System.err:     androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)

System.err:     androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)

System.err:     androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)

System.err:     android.os.Handler.handleCallback(Handler.java:873)

System.err:     android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     android.os.Looper.loop(Looper.java:201)

System.err:     android.app.ActivityThread.main(ActivityThread.java:6810)

System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)

System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

System.err: 

System.err: StackTrace:

System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/com.oracle.iccc.Rolling2Zwrotnik/files/app/vendor.js', line: 131310, column: 38

System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/fragment.js.FragmentClass.onCreateView', file:'file:///data/data/com.oracle.iccc.Rolling2Zwrotnik/files/app/vendor.js', line: 129306, column: 38
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1089)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1081)

System.err: 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)

System.err: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)

System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)

System.err: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)

System.err: 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)

System.err: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)

System.err: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)

System.err: 	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
System.err: 	at android.os.Handler.handleCallback(Handler.java:873)

System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)

System.err: 	at android.os.Looper.loop(Looper.java:201)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6810)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)

System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)

System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
System.err: Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class com.google.android.material.stateful.ExtendableSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x2. Make sure other views do not use the same id.
System.err: 	at android.view.View.onRestoreInstanceState(View.java:18663)
System.err: 	at android.view.View.dispatchRestoreInstanceState(View.java:18635)
System.err: 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3829)
System.err: 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3829)
System.err: 	at android.view.View.restoreHierarchyState(View.java:18613)
System.err: 	... 24 more

```

#### home.component.ts
```
import { Component, OnInit, ChangeDetectionStrategy, OnDestroy } from '@angular/core';
import { Page } from 'tns-core-modules/ui/page/page';
import {
    on as applicationOn,
    suspendEvent,
    resumeEvent,
    ApplicationEventData,
    android as isAndroid,
    launchEvent
} from 'tns-core-modules/application';
import { Subscription, Observable, interval, BehaviorSubject } from 'rxjs';
import * as utils from 'tns-core-modules/utils/utils';
import { device } from 'tns-core-modules/platform';
import { GpsStateService } from '../shared/gps-state.service';
import { NotificationService } from '../backgroundServices/notification.service';
import { JobExecutionService } from '../shared/job-execution.service';
import { NetworkService } from '../shared/network.service';
import { EventsSenderService } from '../shared/events-sender.service';
import { UserService } from '../shared/user.service';
import { StageService } from '../shared/stage.service';
import { Router, NavigationEnd } from '@angular/router';
import { SharedDataService } from './../shared/shared-data.service';
import { Location, distance } from 'nativescript-geolocation';

declare var com: any;

@Component({
    selector: 'Home',
    moduleId: module.id,
    templateUrl: './home.component.html',
    styleUrls: ['home.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class HomeComponent implements OnInit, OnDestroy {

    mapWasLoaded = false;
    isLocaliationStarted = false;

    // starting position
    latitude = 52.230972;
    longitude = 20.980361;

    speed$: BehaviorSubject<string> = new BehaviorSubject('0.0');
    distance: number = 0;
    distance$: BehaviorSubject<string> = new BehaviorSubject('0.0');

    private previousLocation: Location;
    private currentLocation: Location;

    /**
     * geolocation part
     */
    private refreshSubscription: Subscription;
    readonly gpsJobId = 310;
    jobService$: Observable<void>;

    // this could be used to enable get current location
    enableExtra$ = NotificationService.getEnableExtra();

    showAdditionalFabs = false;

    constructor(
        private page: Page,
        private networkService: NetworkService,          // checking network status
        private eventSenderService: EventsSenderService, // init event service
        private userService: UserService,
        private stageService: StageService,
        private sharedDataService: SharedDataService,
        private router: Router,
    ) {
        // checking which event is triggered
        // base on that you can change behaviour of app
        applicationOn(launchEvent, (args: ApplicationEventData) => {
            console.log('launchEvent');
        });

        applicationOn(suspendEvent, (args: ApplicationEventData) => {
            console.log('suspendEvent');
            console.log('isLocaliationStarted: ' + this.isLocaliationStarted);
        });

        applicationOn(resumeEvent, (args: ApplicationEventData) => {
            console.log('resumeEvent');
            console.log('isLocaliationStarted: ' + this.isLocaliationStarted);
        });
    }

    ngOnInit(): void {
        // move to another page later
        this.userService.setName('Dareczek');
        this.stageService.setId(1);
        this.page.actionBarHidden = true;
        GpsStateService.getLatestLocation().subscribe(latestLocation => {
            if (latestLocation) {
                if (this.currentLocation) {
                    this.previousLocation = this.currentLocation;
                }

                this.currentLocation = latestLocation.location;
                this.latitude = latestLocation.location.latitude;
                this.longitude = latestLocation.location.longitude;
                this.speed$.next(this.formatSpeed(latestLocation.location.speed));

                if (this.previousLocation) {
                    this.distance$.next(this.formatDistance(this.calcDistance(this.previousLocation, this.currentLocation)));
                }
            }
        });

        // run job service
        // unsubscribe only in onDestroy()
        this.jobService$ = JobExecutionService.getJobService();
        this.jobService$.subscribe(() => {
            this.startGPSJob();
        });

        // for list view refreshing
        this.refreshSubscription = interval(1000).subscribe();

        this.router.events.subscribe(event => {
            if (event instanceof NavigationEnd) {
                if (event.url === '/home') {
                    // TODO
                } else {
                    // TODO
                }
            }
        });
    }

    ngOnDestroy() {
        this.refreshSubscription.unsubscribe();
        this.stopGPSJob();
        JobExecutionService.stopJobService();
    }

    start() {
        console.log('start()');

        this.isLocaliationStarted = true;

        NotificationService.setStartJobAgain(true);
        JobExecutionService.startJobService();
    }

    stop() {
        console.log('stop()');

        this.isLocaliationStarted = false;

        NotificationService.setStartJobAgain(false);
        this.stopGPSJob();
    }

    handlePhotoButton() {
        this.sharedDataService.addData('selectedPhotosLocation', this.currentLocation);
        this.router.navigate(['/home/post']);
    }

    addEventOnLocation() {
        console.log('addEventOnLocation()');
    }

    showExtraFabs() {
        this.showAdditionalFabs = !this.showAdditionalFabs;
    }

    goToDiagnostic() {
        this.showExtraFabs();
        this.router.navigate(['/home/diagnostic']);
    }

    goToSettings() {
        this.showExtraFabs();
        this.router.navigate(['/home/settings']);
    }

    getTopMargin(type: number): number {
        let topMargin = type === 0 ? 70 : 130;
        topMargin = this.isLocaliationStarted ? topMargin + 110 : topMargin;

        return topMargin;
    }

    calcDistance(location1: Location, location2: Location): number {
        this.distance += distance(location1, location2);

        return this.distance;
    }

    formatDistance(actualDistance: number): string {
        const result = (actualDistance / 1000).toFixed(1);
        console.log('actualDistance: ' + result);

        return result;
    }

    formatSpeed(actualSpeed: number): string {
        const result = (actualSpeed * 3.6).toFixed(1);
        console.log('actualSpeed: ' + result);

        return result;
    }

    startGPSJob() {
        if (isAndroid) {
            const context = utils.ad.getApplicationContext();
            if (device.sdkVersion >= '26') {
                const jobScheduler = context.getSystemService((<any>android.content.Context).JOB_SCHEDULER_SERVICE);
                const component = new android.content.ComponentName(context, com.oracle.iccc.rolling2zwrotnik.location.BackgroundService26.class);
                const builder = new (<any>android.app).job.JobInfo.Builder(this.gpsJobId, component);
                builder.setOverrideDeadline(0);

                return jobScheduler.schedule(builder.build());
            } else {
                const intent = new android.content.Intent(context, com.oracle.iccc.rolling2zwrotnik.location.BackgroundService.class);
                context.startService(intent);
            }
        }
    }

    stopGPSJob() {
        if (isAndroid) {
            if (device.sdkVersion >= '26') {
                this.stopBackgroundJob(this.gpsJobId);
            } else {
                const context = utils.ad.getApplicationContext();
                const intent = new android.content.Intent(context, com.oracle.iccc.rolling2zwrotnik.location.BackgroundService.class);
                context.stopService(intent);
            }
        }
    }

    private stopBackgroundJob(jobId: number) {
        if (isAndroid) {
            const context = utils.ad.getApplicationContext();
            const jobScheduler = context.getSystemService((<any>android.content.Context).JOB_SCHEDULER_SERVICE);
            if (jobScheduler.getPendingJob(jobId) !== null) {
                jobScheduler.cancel(jobId);
                console.log(`Job Canceled: ${jobId}`);
            }
        }
    }
}

```
#### home.component.html
```
<GridLayout class="map-page-wrapper" rows="auto, *">

    <GridLayout height="100%" width="100%">
        <ns-map [latitude]="latitude" [longitude]="longitude"></ns-map>
        <!-- <Image style="height: 70%; width: 70%; opacity: 0.9;" src="res://logo"></Image> -->
    </GridLayout>

    <GridLayout columns="*, *, *" rows="auto, auto">
        <!-- show every time user is offline -->
        <GridLayout height="60" class="offline" col="0" row="0" colSpan="3" *ngIf="!(networkService.isOnline$ | async)">
            <Label class="offline-label lato-light" text="You are offline" textWrap="true"></Label>
        </GridLayout>
        <StackLayout *ngIf="isLocaliationStarted" class="location-header" col="0" row="1" height="112">
            <Label class="location-label" text="Distance" textWrap="true"></Label>
            <StackLayout orientation="horizontal">
                <Label class="location-value lato-light" [text]="distance$ | async" textWrap="true"></Label>
                <Label class="location-value-small" text="km" textWrap="true"></Label>
            </StackLayout>
        </StackLayout>
        <StackLayout *ngIf="isLocaliationStarted" class="location-header" col="1" row="1" height="112">
            <Label class="location-label" text="Speed" textWrap="true"></Label>
            <StackLayout orientation="horizontal">
                <Label class="location-value lato-light" [text]="speed$ | async" textWrap="true"></Label>
                <Label class="location-value-small" text="km/h" textWrap="true"></Label>
            </StackLayout>
        </StackLayout>
        <StackLayout *ngIf="isLocaliationStarted" class="location-header" col="2" row="1" height="112">
            <Label class="location-label" text="GPS" textWrap="true"></Label>
            <Image class="location-value-img" src="res://tick" stretch="none"></Image>
        </StackLayout>
    </GridLayout>

    <!-- fab in top right position -->
    <FAB (tap)="showExtraFabs()" icon="res://avatar" rippleColor="#f1f1f1" class="top-right-fab"
        [style.margin-top]="getTopMargin(0)"> </FAB>
    <FAB (tap)="goToDiagnostic()" *ngIf="showAdditionalFabs" icon="res://debug" rippleColor="#f1f1f1"
        class="top-right-fab-extra-1st" [style.margin-top]="getTopMargin(0)"> </FAB>
    <FAB (tap)="goToSettings()" *ngIf="showAdditionalFabs" icon="res://cog" rippleColor="#f1f1f1"
        class="top-right-fab-extra-2nd" [style.margin-top]="getTopMargin(1)"> </FAB>

    <!-- main fab for start and stop -->
    <FAB *ngIf="!isLocaliationStarted" (tap)="start()" icon="res://play" rippleColor="#f1f1f1" class="fab"> </FAB>
    <FAB *ngIf="isLocaliationStarted" (tap)="stop()" icon="res://stop" rippleColor="#f1f1f1" class="fab"> </FAB>

    <!-- left fab -->
    <FAB (tap)="handlePhotoButton()" icon="res://camera" rippleColor="#f1f1f1" class="left-fab"> </FAB>

    <!-- right fab -->
    <FAB icon="res://placeholder" rippleColor="#f1f1f1" class="right-fab"> </FAB>

</GridLayout>

```

#### map.component.html
```
<MapView #mapView [latitude]="latitude" [longitude]="longitude"
             [zoom]="zoom" [minZoom]="minZoom" [maxZoom]="maxZoom" [bearing]="bearing"
             [tilt]="tilt" i-padding="50,50,50,50" [padding]="padding" (mapReady)="onMapReady($event)"
             (markerSelect)="onMarkerEvent($event)" (markerBeginDragging)="onMarkerEvent($event)"
             (markerEndDragging)="onMarkerEvent($event)" (markerDrag)="onMarkerEvent($event)"
             (markerInfoWindowTapped)="onMarkerEvent($event)" (coordinateTapped)="onCoordinateTapped($event)"
             (cameraChanged)="onCameraChanged($event)"
             (cameraMove)="onCameraMove($event)"></MapView>
```

#### map.component.ts
```
import { Component, Input } from '@angular/core';
import { registerElement } from 'nativescript-angular/element-registry';
import { MapView, Marker, Position, Polyline } from 'nativescript-google-maps-sdk';
import { ImageSource, fromResource } from 'tns-core-modules/image-source';
import { Image } from 'tns-core-modules/ui/image';
import { Color } from 'tns-core-modules/color';
import { stage1 } from '../../shared/stages/geojson/stage1';

declare var org: any;

// Important - must register MapView plugin in order to use in Angular templates
registerElement('MapView', () => MapView);
@Component({
    selector: 'ns-map',
    templateUrl: './map.component.html',
    styleUrls: ['./map.component.scss']
})
export class MapComponent {

    @Input() latitude = 52.230972;
    @Input() longitude = 20.980361;
    zoom = 18;
    minZoom = 0;
    maxZoom = 22;
    bearing = 0;
    tilt = 0;
    padding = [40, 40, 40, 40];
    mapView: MapView;

    lastCamera: String;
    marker: Marker;
    polyline: Polyline;

    constructor() { }

    ngOnInit() {
    }

    // Map events
    onMapReady(event) {

        console.log('Map Ready');

        this.mapView = event.object;

        console.log('Setting a marker...');

        this.marker = new Marker();
        this.marker.position = Position.positionFromLatLng(this.latitude, this.longitude);
        this.marker.title = 'You';
        this.marker.snippet = 'Your position';

        const iconSource: ImageSource = <ImageSource>fromResource('currentposition');
        const icon: Image = new Image();
        icon.imageSource = iconSource;
        this.marker.icon = icon;

        this.marker.userData = { index: 1 };
        this.mapView.addMarker(this.marker);

        this.polyline = new Polyline();
        this.polyline.width = 8;
        this.polyline.color = new Color('#E7264B');
        this.mapView.addPolyline(this.polyline);

        // this.drawPolyline(stage1);
    }

    onCoordinateTapped(args) {
        // console.log('Coordinate Tapped, Lat: ' + args.position.latitude + ', Lon: ' + args.position.longitude, args);
    }

    onMarkerEvent(args) {
        // console.log("Marker Event: '" + args.eventName
        //     + "' triggered on: " + args.marker.title
        //     + ', Lat: ' + args.marker.position.latitude + ', Lon: ' + args.marker.position.longitude, args);
    }

    onCameraChanged(args) {
        // console.log('Camera changed: ' + JSON.stringify(args.camera), JSON.stringify(args.camera) === this.lastCamera);
        this.lastCamera = JSON.stringify(args.camera);
    }

    onCameraMove(args) {
        // console.log('Camera moving: ' + JSON.stringify(args.camera));
        this.updateMarker();
    }

    updateMarker() {
        this.marker.position = Position.positionFromLatLng(this.latitude, this.longitude);
        this.mapView.zoom = this.zoom;
        this.polyline.addPoint(Position.positionFromLatLng(this.latitude, this.longitude));
    }

    drawPolyline(stage: any) {
        const coords: Array<Position> = stage.features[0].geometry.coordinates.map(cords => (Position.positionFromLatLng(cords[1], cords[0])));

        const stagePolyline = new Polyline();
        stagePolyline.width = 8;
        stagePolyline.color = new Color('#E7264B');
        stagePolyline.addPoints(coords);
        console.log('cords length: ' + coords.length);

        this.mapView.addPolyline(stagePolyline);

        // this.createMarker(2, coords[0].lat, coords[0].lng, 'Start', 'Starting position');
        // this.createMarker(3, coords[coords.length - 1].lat, coords[coords.length - 1].lng, 'Final', 'Final position');

        // this.map.addMarkers(Array.from(this.markers.values()));
    }
}
```

#### post.component.ts
```
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { Location } from '@angular/common';
import { reverseMapping, createEvent } from '~/app/shared/utils/utils';
import { ImageAsset } from 'tns-core-modules/image-asset/image-asset';
import { SharedDataService } from './../../shared/shared-data.service';
import { Page, EventData } from 'tns-core-modules/ui/page';
import eventCategories from '../../shared/static/lovs/eventCategories.json';
import { action, alert } from 'tns-core-modules/ui/dialogs';
import { StageService } from './../../shared/stage.service';
import { UserService } from '~/app/shared/user.service';
import { createEventParam } from './../../shared/utils/utils';
import { EventsSenderService } from './../../shared/events-sender.service';
import { ImagepickerService } from './../../shared/imagepicker.service';
import { CameraService } from './../../shared/camera.service';

@Component({
    selector: 'ns-post',
    templateUrl: './post.component.html',
    styleUrls: ['./post.component.scss']
})
export class PostComponent implements OnInit {
    private readonly categoryPlaceholder = 'Select your post category..';
    selectedImages: ImageAsset[] = [];
    thumbSize: number = 88;
    thumbSize2: number = this.thumbSize + 2;
    previewSize: number = 300;
    postText = '';
    private category = '';
    private currentLocation;
    selectedCategory = this.categoryPlaceholder;

    constructor(
        private page: Page,
        private sharedDataService: SharedDataService,
        private ref: ChangeDetectorRef,
        private userService: UserService,
        private stageService: StageService,
        private eventSenderService: EventsSenderService,
        private location: Location,
        private imagepickerService: ImagepickerService,
        private cameraService: CameraService
    ) { }

    ngOnInit() {
        this.page.actionBarHidden = false;
        this.currentLocation = {
            ...this.sharedDataService.getData('selectedPhotosLocation')
        };
        this.sharedDataService.removeData('selectedPhotosLocation');
    }

    handleShareButton(args: EventData) {
        if (this.currentLocation) {
            let event = createEvent(
                this.currentLocation,
                this.userService.getName(),
                this.stageService.getId()
            );
            // Create COMMENT param
            console.log('COMMENT', this.postText);
            event.evt_parameters.push(
                createEventParam('COMMENT', 'STRING', '', this.postText)
            );
            // Create POI param
            event.evt_parameters.push(
                createEventParam('POI', 'STRING', '', this.category)
            );
            const eventDb = this.eventSenderService.createDbEvent(
                event,
                this.selectedImages.map(img => img.android)
            );
            this.eventSenderService.sendEventImages(eventDb);

            alert({
                title: 'Post processed',
                message: 'Your post has been processed.',
                okButtonText: 'OK'
            }).then(() => {
                console.log('powinien wrocic');
            });
        }
    }

    handleCategoryButton(args: EventData) {
        this.showCategoryDialog();
    }

    handleImageTap(args: EventData, img: ImageAsset) {
        this.selectedImages = this.selectedImages.filter(
            elem => elem.android != img.android
        );
    }

    showCategoryDialog() {
        const reversedLOV = reverseMapping(eventCategories);
        const actions = Object.values(eventCategories);
        let options = {
            title: 'Event Category',
            cancelButtonText: 'Cancel',
            actions
        };
        const that = this;
        action(options).then(result => {
            // if to avoid using Cancel button value
            if (actions.includes(result)) {
                that.category = reversedLOV[result];
                that.selectedCategory = result ? result : '';
                that.ref.detectChanges();
            }
        });
    }

    selectImageFromDevice() {
        this.imagepickerService
            .showImagepicker('multiple')
            .then(selection => {
                selection.forEach(img => this.addImageAsset(img));
                this.ref.detectChanges();
            })
            .catch(e => { });
    }

    addImageAsset(img: ImageAsset) {
        if (!this.selectedImages.find(elem => elem.android === img.android))
            this.selectedImages.push(img);
    }

    handlePhotoButton() {
        this.cameraService.showDeviceCamera().then(result => {
            if (result instanceof Error) {
                console.log('Camera cancelled ...');
            } else {
                this.selectedImages.push(result);
                this.ref.detectChanges();
            }
        });
    }

    goBack() {
        this.location.back();
    }
}

```

**Comment by trevortos** [comment]
You can setup a "application.resumeEvent" and "application.suspendEvent" listener, and for Android only, call "mapView.nativeView.onResume()" and "mapView.nativeView.onPause()" I put a bit of a delay on them, and it seems to help.

**Comment by tripper-app** [comment]
> You can setup a "application.resumeEvent" and "application.suspendEvent" listener, and for Android only, call "mapView.nativeView.onResume()" and "mapView.nativeView.onPause()" I put a bit of a delay on them, and it seems to help.

Can you please elaborate your answer? i have the same problem and no clue how to solve it
