### ISSUE TITLE
Calling js method onCreateView failed

### ISSUE THREAD

**Issue by mannok** [dapriett/nativescript-google-maps-sdk#371]
Hi

I wonder why I encounter such error. I have just created a new vue project and went through all the steps from the tutorial. When I start the project with `tns preview`, error prompt as following.

```
Calling js method onCreateView failed
TypeError: Cannot read property 'model' of undefined

StackTrace:
	MapView._createCameraPosition(file:///data/data/org.nativescript.preview/files/app/vendor.js:1063:53)
	at MapView.createNativeView(file:///data/data/org.nativescript.preview/files/app/vendor.js:847:31)
	at ViewBase._setupUI(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:492:25)
	at (file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:534:13)
	at LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:20)
	at ViewCommon.eachChild(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js:1010:10)
	at ViewBase._setupUI(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:533:10)
	at (file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:534:13)
	at ContentView.eachChildView(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js:70:7)
	at PageBase.eachChildView(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/page/page-common.js:126:36)
	at ViewCommon.eachChild(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js:1010:10)
	at ViewBase._setupUI(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:533:10)
	at ViewBase._addViewCore(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:432:12)
	at ViewBase._addView(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:421:10)
	at FragmentCallbacksImplementation.onCreateView(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js:687:13)
	at FragmentClass.onCreateView(file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js:26:34)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
	at com.tns.Runtime.callJSMethod(Runtime.java:1083)
	at com.tns.Runtime.callJSMethod(Runtime.java:1063)
	at com.tns.Runtime.callJSMethod(Runtime.java:1055)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:54)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by sritam144** [comment]
Actually problem in Preview app , not in your code . If you run Locally means in your android phone by using USB cable it's working fine for me .
