### ISSUE TITLE
TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by Nargott** [dapriett/nativescript-google-maps-sdk#377]
Hi. Cannot use nativescript-google-maps-sdk with Nativescript-Vue. I've gone through all the steps from the tutorial. When I start the project with _tns preview_, got the next crash:

`LOG from device OnePlus 7 Pro: com.tns.NativeScriptException: Error calling module function 
TypeError: Cannot read property 'extend' of undefined
File: (/data/data/org.nativescript.preview/files/internal/ts_helpers.js:51:35)

StackTrace:
        __extends(/data/data/org.nativescript.preview/files/internal/ts_helpers.js:51:36)
        at (file:///data/data/org.nativescript.preview/files/app/vendor.js:1022:3)
        at ../node_modules/nativescript-google-maps-sdk/map-view.js(file:///data/data/org.nativescript.preview/files/app/vendor.js:1524:2)
        at __webpack_require__(file:///data/data/org.nativescript.preview/files/app/runtime.js:754:30)
        at fn(file:///data/data/org.nativescript.preview/files/app/runtime.js:121:20)
        at ../node_modules/nativescript-google-maps-sdk/map-view-common.js(file:///data/data/org.nativescript.preview/files/app/vendor.js:379:18)
        at __webpack_require__(file:///data/data/org.nativescript.preview/files/app/runtime.js:754:30)
        at fn(file:///data/data/org.nativescript.preview/files/app/runtime.js:121:20)
        at ../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/index.js?!./components/HelloWorld.vue?vue&type=script&lang=js&(file:///data/data/org.nativescript.preview/files/app/bundle.js:9:102)   
        at __webpack_require__(file:///data/data/org.nativescript.preview/files/app/runtime.js:754:30)
        at fn(file:///data/data/org.nativescript.preview/files/app/runtime.js:121:20)
        at ./components/HelloWorld.vue?vue&type=script&lang=js&(file:///data/data/org.nativescript.preview/files/app/bundle.js:540:193)
        at __webpack_require__(file:///data/data/org.nativescript.preview/files/app/runtime.js:754:30)
        at fn(file:///data/data/org.nativescript.preview/files/app/runtime.js:121:20)
        at ./components/HelloWorld.vue(file:///data/data/org.nativescript.preview/files/app/bundle.js:488:98)
        at __webpack_require__(file:///data/data/org.nativescript.preview/files/app/runtime.js:754:30)
        at fn(file:///data/data/org.nativescript.preview/files/app/runtime.js:121:20)
        at (file:///data/data/org.nativescript.preview/files/app/bundle.js:415:80)
        at ./app.js(file:///data/data/org.nativescript.preview/files/app/bundle.js:478:30)
        at __webpack_require__(file:///data/data/org.nativescript.preview/files/app/runtime.js:754:30)
        at checkDeferredModules(file:///data/data/org.nativescript.preview/files/app/runtime.js:44:23)
        at webpackJsonpCallback(file:///data/data/org.nativescript.preview/files/app/runtime.js:31:19)
        at (file:///data/data/org.nativescript.preview/files/app/bundle.js:2:57)
        at require(:1:266)

TypeError: Cannot read property 'extend' of undefined
        at com.tns.Runtime.runModule(Native Method)
        at com.tns.Runtime.runModule(Runtime.java:662)
        at com.tns.Runtime.run(Runtime.java:654)
        at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1197)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6647)
        at android.app.ActivityThread.access$1600(ActivityThread.java:231)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

Any ideas?

**Comment by Jordan9500** [comment]
@Nargott Did you manage to fix this issue?

**Comment by bugMaker-237** [comment]
Any updates about the issue ?
