### ISSUE TITLE
The demo app crashed on start

### ISSUE THREAD

**Issue by ryc16** [dapriett/nativescript-google-maps-sdk#41]
Followed the instruction to build the demo for Android (tied on both emulator and real android device). Did installed both "Google Repository" and "Google Play services" from SDK Manager, and was able to build.

> BUILD SUCCESSFUL
> 
> Total time: 39.671 secs
> Project successfully built
> Transferring project files...

However, got error "Unfortunately, googlemapdemo2 has stopped." 

So check the log 

> />adb logcat

```
--------- beginning of /dev/log/main
D/dalvikvm(  740): GC_FOR_ALLOC freed 1750K, 36% free 8104K/12496K, paused 9ms, total 9ms
D/dalvikvm(  740): GC_FOR_ALLOC freed 379K, 32% free 8585K/12496K, paused 15ms, total 15ms
--------- beginning of /dev/log/system
W/ActivityManager(  740): Activity pause timeout for ActivityRecord{529e4878 u0 org.nativescript.googlemapdemo2/com.tns.NativeScriptActivity t47 f}
W/EGL_xap (  966): eglSurfaceAttrib not implemented
E/WindowManager(  740): Starting window AppWindowToken{52c0a9b4 token=Token{529e4928 ActivityRecord{529e4878 u0 org.nativescript.googlemapdemo2/com.tns.NativeScriptActivity t47}}} timed out
W/ActivityManager(  740): Activity destroy timeout for ActivityRecord{529e4878 u0 org.nativescript.googlemapdemo2/com.tns.NativeScriptActivity t47 f}
```

> />tns info

```
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.0.1           │ 2.0.1          │ Up to date    │
│ tns-core-modules │ 2.0.1           │ 2.0.1          │ Up to date    │
│ tns-android      │ 2.0.0           │ 2.0.0          │ Up to date    │
│ tns-ios          │                 │ 2.0.1          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

package.json

```
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.googlemapdemo2",
		"tns-android": {
			"version": "2.0.0"
		}
	},
	"dependencies": {
		"nativescript-google-maps-sdk": "^1.3.1",
		"tns-core-modules": "2.0.1"
	},
	"devDependencies": {
		"babel-traverse": "6.9.0",
		"babel-types": "6.10.0",
		"babylon": "6.8.1",
		"filewalker": "0.1.2",
		"lazy": "1.0.11"
	}
}
```
Any idea?

**Comment by ignaciolarranaga** [comment]
+1

**Comment by einicher** [comment]
on which platform are you building?

**Comment by ryc16** [comment]
Android as indicated on my first post

/>tns info

```
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.0.1           │ 2.0.1          │ Up to date    │
│ tns-core-modules │ 2.0.1           │ 2.0.1          │ Up to date    │
│ tns-android      │ 2.0.0           │ 2.0.0          │ Up to date    │
│ tns-ios          │                 │ 2.0.1          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

**Comment by dapriett** [comment]
Not sure why it wouldn't work - have you tried running the demo in this repo? https://github.com/dapriett/nativescript-google-maps-sdk/tree/master/demo

**Comment by einicher** [comment]
i ment the host system you are building it on.
i had that problem too, ran it in android studio and got the error, that applicationId was missing in the gradle.build file. Added the id, then also there was something wrong with a java lib in ubuntu: 
http://stackoverflow.com/questions/33439905/is-the-cacerts-file-missing-in-ubuntu-15-10-and-openjdk-8-jdk
After these changes it worked for me, no more crashes. Maybe it helps you too somehow.

**Comment by ryc16** [comment]
Thanks for getting back to me.

@dapriett, yup, I was. I try again today with 2 different ways shown below. Here is my attempts. @einicher, it is windows 10.
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_92
Android SDK = 25.1.7

Attempt 1:

>git clone https://github.com/dapriett/nativescript-google-maps-sdk.git google-map-demo4
>cd google-map-demo4\demo
>npm install
>tns platform add android
>adb logcat -c
>adb logcat
>tns livesync android --watch

```
The depedency located at C:\codeprojs\NativeScript\2plugins\google-map-demo4\demo\node_modules\babel-runtime\node_modules\core-js with version  1.2.6 will be replaced with dependency located at C:\codeprojs\NativeScript\2plugins\google-map-demo4\demo\node_modules\core-js with version 2.4.0
Successfully prepared plugin nativescript-google-maps-sdk for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared
Transferring project files...
Successfully transferred all project files.
Applying changes...
Successfully synced application org.nativescript.demo on device 10.71.34.101:5555.
W/System.err( 7692): java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
W/System.err( 7692): Caused by: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
W/System.err( 7692):    at com.tns.Runtime.createJSInstanceNative(Native Method)
W/System.err( 7692):    at com.tns.Runtime.createJSInstance(Runtime.java:367)
```

```
--------- beginning of /dev/log/main
D/AndroidRuntime( 7378):
D/AndroidRuntime( 7378): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 7378): CheckJNI is OFF
D/dalvikvm( 7378): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 7378): Added shared lib libjavacore.so 0x0
D/dalvikvm( 7378): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 7378): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 7378): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
E/cutils-trace( 7378): Error opening trace file: No such file or directory (2)
D/dalvikvm( 7378): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/memtrack( 7378): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 7378): failed to load memtrack module: -2
D/AndroidRuntime( 7378): Calling main entry com.android.commands.pm.Pm
D/AndroidRuntime( 7378): Shutting down VM
D/dalvikvm( 7378): GC_CONCURRENT freed 235K, 30% free 558K/796K, paused 0ms+1ms, total 1ms
D/AndroidRuntime( 7669):
D/AndroidRuntime( 7669): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 7669): CheckJNI is OFF
D/dalvikvm( 7669): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 7669): Added shared lib libjavacore.so 0x0
D/dalvikvm( 7669): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 7669): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 7669): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
D/dalvikvm( 7669): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/cutils-trace( 7669): Error opening trace file: No such file or directory (2)
E/memtrack( 7669): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 7669): failed to load memtrack module: -2
D/AndroidRuntime( 7669): Calling main entry com.android.commands.am.Am
D/AndroidRuntime( 7669): Shutting down VM
--------- beginning of /dev/log/system
I/ActivityManager( 1020): Force stopping org.nativescript.demo appid=10095 user=0: from pid 7669
D/dalvikvm( 7669): GC_CONCURRENT freed 91K, 15% free 544K/640K, paused 0ms+0ms, total 1ms
D/AndroidRuntime( 7680):
D/AndroidRuntime( 7680): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 7680): CheckJNI is OFF
D/dalvikvm( 7680): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 7680): Added shared lib libjavacore.so 0x0
D/dalvikvm( 7680): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 7680): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 7680): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
E/cutils-trace( 7680): Error opening trace file: No such file or directory (2)
D/dalvikvm( 7680): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/memtrack( 7680): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 7680): failed to load memtrack module: -2
D/AndroidRuntime( 7680): Calling main entry com.android.commands.am.Am
I/ActivityManager( 1020): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=org.nativescript.demo/com.tns.NativeScriptActivity} from pid 7680
D/dalvikvm( 1020): GC_FOR_ALLOC freed 1720K, 37% free 6994K/10940K, paused 13ms, total 13ms
D/AndroidRuntime( 7680): Shutting down VM
D/dalvikvm( 7680): GC_CONCURRENT freed 95K, 15% free 576K/676K, paused 0ms+0ms, total 1ms
D/dalvikvm( 7692): Late-enabling CheckJNI
I/ActivityManager( 1020): Start proc org.nativescript.demo for activity org.nativescript.demo/com.tns.NativeScriptActivity: pid=7692 uid=10095 gids={50095, 1028, 1015, 3003}
D/dalvikvm( 7692): Trying to load lib /data/app-lib/org.nativescript.demo-1/libNativeScript.so 0xa50239b0
D/dalvikvm( 7692): Added shared lib /data/app-lib/org.nativescript.demo-1/libNativeScript.so 0xa50239b0
I/TNS.Native( 7692): NativeScript Runtime Version 2.0.0, commit 897767022ea883ed5419624af02d61821c9e3317
D/TNS.Native( 7692): JNI_ONLoad
D/TNS.Native( 7692): JNI_ONLoad END
D/dalvikvm( 7692): GC_CONCURRENT freed 420K, 16% free 2886K/3432K, paused 5ms+3ms, total 30ms
D/dalvikvm( 7692): GC_CONCURRENT freed 426K, 16% free 2918K/3448K, paused 1ms+0ms, total 4ms
D/dalvikvm( 7692): GC_CONCURRENT freed 419K, 16% free 2897K/3448K, paused 2ms+1ms, total 9ms
D/dalvikvm( 7692): GC_CONCURRENT freed 393K, 16% free 2915K/3448K, paused 2ms+1ms, total 9ms
D/dalvikvm( 7692): GC_CONCURRENT freed 438K, 17% free 2898K/3452K, paused 2ms+2ms, total 11ms
D/dalvikvm( 7692): GC_CONCURRENT freed 347K, 17% free 2940K/3520K, paused 2ms+3ms, total 13ms
D/TNS.Native( 7692): V8 version 4.7.80
D/TNS.Native( 7692): lenNodes=61392, lenNames=666647, lenValues=748181
D/TNS.Native( 7692): time=2
D/dalvikvm( 7692): GC_CONCURRENT freed 372K, 16% free 2989K/3520K, paused 0ms+1ms, total 4ms
D/AndroidRuntime( 7692): Shutting down VM
W/dalvikvm( 7692): threadid=1: thread exiting with uncaught exception (group=0xa4d3db20)
W/System.err( 7692): java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
W/System.err( 7692):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4347)
W/System.err( 7692):    at android.app.ActivityThread.access$1500(ActivityThread.java:135)
D/dalvikvm( 7692): GC_CONCURRENT freed 406K, 16% free 2975K/3520K, paused 1ms+0ms, total 6ms
W/System.err( 7692):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
W/System.err( 7692):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 7692):    at android.os.Looper.loop(Looper.java:136)
W/System.err( 7692):    at android.app.ActivityThread.main(ActivityThread.java:5017)
W/System.err( 7692):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 7692):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 7692):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
W/System.err( 7692):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
W/System.err( 7692):    at dalvik.system.NativeStart.main(Native Method)
W/System.err( 7692): Caused by: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
W/System.err( 7692):    at com.tns.Runtime.createJSInstanceNative(Native Method)
W/System.err( 7692):    at com.tns.Runtime.createJSInstance(Runtime.java:367)
W/System.err( 7692):    at com.tns.Runtime.initInstance(Runtime.java:342)
W/System.err( 7692):    at com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:128)
W/System.err( 7692):    at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:13)
W/System.err( 7692):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
W/System.err( 7692):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
W/System.err( 7692):    ... 10 more
I/ActivityManager( 1020): START u0 {flg=0x14008000 cmp=org.nativescript.demo/com.tns.ErrorReportActivity (has extras)} from pid -1
W/WindowManager( 1020): Screenshot failure taking screenshot for (768x1280) to layer 21010
I/WindowManager( 1020): Screenshot max retries 4 of Token{529cc420 ActivityRecord{529d4c24 u0 org.nativescript.demo/com.tns.NativeScriptActivity t18 f}} appWin=Window{52a42458 u0 Starting org.nativescript.demo} drawState=4
I/Process ( 7692): Sending signal. PID: 7692 SIG: 9
I/ActivityManager( 1020): Process org.nativescript.demo (pid 7692) has died.
D/dalvikvm( 7716): Late-enabling CheckJNI
D/dalvikvm(  612): GC_EXPLICIT freed 41K, 6% free 2837K/3004K, paused 0ms+0ms, total 4ms
I/ActivityManager( 1020): Start proc org.nativescript.demo for activity org.nativescript.demo/com.tns.ErrorReportActivity: pid=7716 uid=10095 gids={50095, 1028, 1015, 3003}
D/dalvikvm(  612): GC_EXPLICIT freed <1K, 6% free 2837K/3004K, paused 1ms+1ms, total 10ms
D/dalvikvm(  612): GC_EXPLICIT freed <1K, 6% free 2837K/3004K, paused 1ms+1ms, total 21ms
D/dalvikvm( 7716): Trying to load lib /data/app-lib/org.nativescript.demo-1/libNativeScript.so 0xa50247d0
D/dalvikvm( 7716): Added shared lib /data/app-lib/org.nativescript.demo-1/libNativeScript.so 0xa50247d0
I/TNS.Native( 7716): NativeScript Runtime Version 2.0.0, commit 897767022ea883ed5419624af02d61821c9e3317
D/TNS.Native( 7716): JNI_ONLoad
D/TNS.Native( 7716): JNI_ONLoad END
D/libEGL  ( 7716): loaded /system/lib/egl/libEGL_xap.so
D/eglCodecCommon( 7716): TcpStream::connect() - management hostname is 10.71.34.101
D/eglCodecCommon( 7716): TcpStream::connect() - connecting host: 10.71.34.1
D/        ( 7716): HostConnection::get() New Host Connection established 0xb90b7c60, tid 7716
D/libEGL  ( 7716): loaded /system/lib/egl/libGLESv1_CM_xap.so
D/libEGL  ( 7716): loaded /system/lib/egl/libGLESv2_xap.so
W/EGL_xap ( 7716): eglSurfaceAttrib not implemented
E/OpenGLRenderer( 7716): Getting MAX_TEXTURE_SIZE from GradienCache
E/OpenGLRenderer( 7716): MAX_TEXTURE_SIZE: 8192
E/OpenGLRenderer( 7716): Getting MAX_TEXTURE_SIZE from Caches::initConstraints()
E/OpenGLRenderer( 7716): MAX_TEXTURE_SIZE: 8192
D/OpenGLRenderer( 7716): Enabling debug mode 0
I/ActivityManager( 1020): Displayed org.nativescript.demo/com.tns.ErrorReportActivity: +857ms (total +2s45ms)
D/dalvikvm( 1020): GC_CONCURRENT freed 510K, 33% free 7400K/10940K, paused 1ms+1ms, total 11ms

```

Attempt 2:
>tns create google-map-demo5
>cd google-map-demo5
>tns plugin add nativescript-google-maps-sdk
copy demo4's files ie app.*, main-page.*, main-view-model.* to demo5
>tns platform add android
>adb logcat -c
>adb logcat
>tns livesync android --watch

```
BUILD SUCCESSFUL

Total time: 5 mins 36.65 secs
Project successfully built
```
logs:
```
--------- beginning of /dev/log/main
D/dalvikvm( 1020): GC_CONCURRENT freed 1845K, 32% free 6978K/10196K, paused 4ms+1ms, total 26ms
D/AndroidRuntime( 7751):
D/AndroidRuntime( 7751): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 7751): CheckJNI is OFF
D/dalvikvm( 7751): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 7751): Added shared lib libjavacore.so 0x0
D/dalvikvm( 7751): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 7751): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 7751): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
D/dalvikvm( 7751): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/cutils-trace( 7751): Error opening trace file: No such file or directory (2)
E/memtrack( 7751): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 7751): failed to load memtrack module: -2
D/AndroidRuntime( 7751): Calling main entry com.android.commands.pm.Pm
D/AndroidRuntime( 7751): Shutting down VM
D/dalvikvm( 7751): GC_CONCURRENT freed 235K, 30% free 558K/796K, paused 1ms+0ms, total 2ms
--------- beginning of /dev/log/system
I/ProcessStatsService( 1020): Prepared write state in 1ms
I/ProcessStatsService( 1020): Prepared write state in 1ms
D/ConnectivityService( 1020): Sampling interval elapsed, updating statistics ..
D/ConnectivityService( 1020): Done.
D/ConnectivityService( 1020): Setting timer for 720seconds
D/AndroidRuntime( 7762):
D/AndroidRuntime( 7762): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 7762): CheckJNI is OFF
D/dalvikvm( 7762): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 7762): Added shared lib libjavacore.so 0x0
D/dalvikvm( 7762): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 7762): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 7762): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
E/cutils-trace( 7762): Error opening trace file: No such file or directory (2)
D/dalvikvm( 7762): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/memtrack( 7762): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 7762): failed to load memtrack module: -2
D/AndroidRuntime( 7762): Calling main entry com.android.commands.pm.Pm
W/PackageManager( 1020): Package named 'org.nativescript.googlemapdemo5' doesn't exist.
D/dalvikvm( 1020): GC_EXPLICIT freed 265K, 32% free 6976K/10196K, paused 2ms+1ms, total 15ms
D/AndroidRuntime( 7762): Shutting down VM
D/dalvikvm( 7762): GC_CONCURRENT freed 92K, 15% free 549K/644K, paused 0ms+0ms, total 1ms
D/AndroidRuntime( 7776):
D/AndroidRuntime( 7776): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 7776): CheckJNI is OFF
D/dalvikvm( 7776): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 7776): Added shared lib libjavacore.so 0x0
D/dalvikvm( 7776): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 7776): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 7776): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
D/dalvikvm( 7776): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/cutils-trace( 7776): Error opening trace file: No such file or directory (2)
E/memtrack( 7776): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 7776): failed to load memtrack module: -2
D/AndroidRuntime( 7776): Calling main entry com.android.commands.pm.Pm
I/ActivityManager( 1020): Start proc com.android.defcontainer for service com.android.defcontainer/.DefaultContainerService: pid=7786 uid=10003 gids={50003, 1028, 1015, 1023, 2001, 1035}
E/PackageParser( 7786): parsePackageLite error: <manifest> specifies bad package name "__PACKAGE__": bad character '_'
W/DefContainer( 7786): Failed to parse package
W/ActivityManager( 1020): No content provider found for permission revoke: file:///data/local/tmp/googlemapdemo5-debug.apk
D/dalvikvm( 1020): GC_EXPLICIT freed 15K, 32% free 6977K/10196K, paused 1ms+1ms, total 15ms
D/AndroidRuntime( 7776): Shutting down VM
D/dalvikvm( 7776): GC_CONCURRENT freed 122K, 19% free 559K/684K, paused 3ms+0ms, total 4ms
D/AndroidRuntime( 7804):
D/AndroidRuntime( 7804): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 7804): CheckJNI is OFF
D/dalvikvm( 7804): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 7804): Added shared lib libjavacore.so 0x0
D/dalvikvm( 7804): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 7804): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 7804): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
D/dalvikvm( 7804): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
E/cutils-trace( 7804): Error opening trace file: No such file or directory (2)
E/memtrack( 7804): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 7804): failed to load memtrack module: -2
D/AndroidRuntime( 7804): Calling main entry com.android.commands.am.Am
I/ActivityManager( 1020): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=org.nativescript.googlemapdemo5/com.tns.NativeScriptActivity} from pid 7804
D/AndroidRuntime( 7804): Shutting down VM
D/dalvikvm( 7804): GC_CONCURRENT freed 96K, 15% free 576K/676K, paused 0ms+0ms, total 1ms
I/ActivityManager( 1020): Killing 1556:com.android.calendar/u0a20 (adj 15): empty for 45712s
```

**Comment by dapriett** [comment]
What devices/emulators and Android versions you running this on?

**Comment by ryc16** [comment]
@dapriett,

I was using Xamarin Android Player running Nexus 4 (KitKat). Try on device Samsung Note 2 with v4.4.2 just right now and crashed.

**Comment by ryc16** [comment]
After upgrade to nativescript 2.1.0, no longer encounter the problem. Works now. Thanks

**Comment by dapriett** [comment]
Great - thanks for the update.
