### ISSUE TITLE
Crash since updating

### ISSUE THREAD

**Issue by mrwrighty** [dapriett/nativescript-google-maps-sdk#457]
Old app worked fine with NS6 and NS7. Had to mod project so updated to Nativescript 7.1.2

Application refuses to load any page with a mapView defined. Upgraded to and nativescript-google-maps-sdk version 3.0.2 and now get this crash report when running ns debug iOS: -

NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined
at
(file: node_modules/nativescript-google-maps-sdk/map-view.ios.js:49:0)
at ../node_modules/nativescript-google-maps-sdk/map-view.js(file:///app/vendor.js:65443:30)
at __webpack_require__(file: app/webpack/bootstrap:816:0)
at fn(file: app/webpack/bootstrap:120:0)
at (file: app/app.js:41:18)
at ./app.js(file:///app/bundle.js:221:30)
at __webpack_require__(file: app/webpack/bootstrap:816:0)
at checkDeferredModules(file: app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
at (file:///app/bundle.js:2:57)
at require(:1:137)
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined
at
(file: node_modules/nativescript-google-maps-sdk/map-view.ios.js:49:0)
at ../node_modules/nativescript-google-maps-sdk/map-view.js(file:///app/vendor.js:65443:30)
at __webpack_require__(file: app/webpack/bootstrap:816:0)
at fn(file: app/webpack/bootstrap:120:0)
at (file: app/app.js:41:18)
at ./app.js(file:///app/bundle.js:221:30)
at __webpack_require__(file: app/webpack/bootstrap:816:0)
at checkDeferredModules(file: app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: app/webpack/bootstrap:30:0)
at (file:///app/bundle.js:2:57)
at require(:1:137)

**Comment by mrwrighty** [comment]
Ok this is a repeat of https://github.com/dapriett/nativescript-google-maps-sdk/issues/452

Not fixed in 3.0.2

**Comment by OPADA-Eng** [comment]
Any solution other than the workaround?
